const admins_schema = require('./AdminSchema')
const affliated_colleges_schema = require('./AffliatedCollegesSchema')
const notification_updates_schema = require('./UpdatesSchema')
const dmc_upload_schema = require('./DMCUploadSchema')
const event_photos_table = require('./EventPhotosSchema')
const carousel_photos_table=  require('./CarouselSchema')
const gallery_requests_table =require('./galleryRequestsSchema')
const directors_table = require('./DirectorsSchema')
const admin_email_allowlist = require('./AdminEmailAllowlistSchema')
const admin_profile_schema = require('./AdminProfileSchema')
const site_nav_schema = require('./SiteNavSchema')
const youtube_videos_schema = require('./YoutubeVideosSchema')
const press_notes_schema = require('./PressNotesSchema')
const executive_council_schema = require('./ExecutiveCouncilSchema')
const website_leadership_profile_schema = require('./WebsiteLeadershipProfileSchema')
const website_people_schema = require('./WebsitePeopleSchema')
const website_position_assignment_schema = require('./WebsitePositionAssignmentSchema')

exports.allSchemas = ()=>{
    
    admins_schema.admin_table()
    notification_updates_schema.notification_updates_table()
    affliated_colleges_schema.affiliated_colleges_table()
    dmc_upload_schema.dmc_upload_table()
    event_photos_table.event_photos_table()
    carousel_photos_table.carousel_photos_table()
    gallery_requests_table.gallery_requests()
    directors_table.directors_table()
    admin_email_allowlist.admin_email_allowlist_table()
    admin_profile_schema.admin_profile_table()
    site_nav_schema.site_nav_table()
    youtube_videos_schema.youtube_videos_table()
    press_notes_schema.press_notes_table()
    executive_council_schema.executive_council_table()
    website_leadership_profile_schema.website_leadership_profiles_table()
    website_people_schema.website_people_table()
    website_position_assignment_schema.website_position_assignments_table()

}
